In [1]:
import numpy as np
import pandas as pd

In [2]:
#Creating DataFrame
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [3]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [4]:
# Selecting columns
df[["Name" , "Age"]]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [13]:
# Creating new columns
df["Role"] = ["Ai Engineer" , "Doctor" , "Manager", "Devolper"]

In [14]:
df

    Name  Age      City  Salary         Role
0   John   28  New York   65000  Ai Engineer
1   Anna   34     Paris   70000       Doctor
2  Peter   29    Berlin   62000      Manager
3  Linda   42    London   85000     Devolper

In [15]:
# Removing column
df.drop(columns="Role" , axis=1,inplace=True)

In [16]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [17]:
# Selecting Row
df.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [18]:
df.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [19]:
df.iloc[1]

Name       Anna
Age          34
City      Paris
Salary    70000
Name: 1, dtype: object

In [20]:
# Selecting Subet of row and columns
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [21]:
df.loc[[2,3]][["Name", "Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [22]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [23]:
# Condition Selection
# Select the person who has age of 30 and must from Paris
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [24]:
df[(df['Age'] > 30) & (df['City'] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

In [25]:
df[df["Name"] == 'John']

   Name  Age      City  Salary
0  John   28  New York   65000