In [1]:
import numpy as np
import pandas as pd

In [2]:
my_list = [10,20,30]
labels = ['a','b','c']
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [3]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [5]:
pd.Series(data = my_list , index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64